### ISSUE TITLE
Strange `custom` behaviour when dimensions are not matched.

### ISSUE THREAD

**Issue by ivan-krukov** [omarwagih/ggseqlogo#1]
Hello!

Thank you for an excellent package.

I have stumbled on a strange behaviour while using `method="custom"` with an unexpected number of elements. Here is an example:

```R
set.seed(123)
silly <- list(c("T","C","G","A", "A"))
matrix( rexp(5 * 3), nrow = 5, dimnames=silly) %>% 
ggseqlogo(seq_type='dna', method='custom')
```
![wut](https://user-images.githubusercontent.com/1881263/26995394-a66c8076-4d29-11e7-8e37-70d9e2fa00a7.png)

I know this is a strange example, since the dimensions are mismatched. Should there be an input check, or perhaps a [group](https://github.com/heike/gglogo/blame/master/README.md#L18) option?

**Comment by omarwagih** [comment]
Thanks for pointing this out. Duplicate row names shouldn't be allowed. I've added an input check [in the latest commit](https://github.com/omarwagih/ggseqlogo/commit/079e783b18d48a336f8ef588cdad4c2d49353af0).
