### ISSUE TITLE
Version of LGPL?

### ISSUE THREAD

**Issue by smoe** [omarwagih/ggseqlogo#18]
Dear @omarwagih,
It is scientifically so very unimportant, please forgive, but if you could please be explicit about the exact version of the LGPL you decided to distribute ggseqlogo with, this would help with its redistribution. Options are:
License: LGPL (>= 2)
License: LGPL (>= 3)
License: LGPL-2
License: LGPL-3
from https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file section 1.1.2.
Many thanks - and - sorry for this noise.
Steffen

**Comment by omarwagih** [comment]
Hi Steffen, you can assume LGPL-3. I have pushed this update to github and it'll be a part of subsequent releases on CRAN. Thanks
