### ISSUE TITLE
Small Sample Correction Not working

### ISSUE THREAD

**Issue by jglavina** [omarwagih/ggseqlogo#2]
Excellent package and completely useful.
The IC content is being plot without small sample correction.
Here is the plot created by ggseqlogo

![qqseqlogoplot](https://user-images.githubusercontent.com/1714534/28172361-b9878414-67c1-11e7-862e-90718ef06d0d.png)

and here the plot using weblogo and small sample correction
![weblogoplot](https://user-images.githubusercontent.com/1714534/28172387-cc56a0ac-67c1-11e7-9575-681548698b86.png)

**Comment by omarwagih** [comment]
Thanks Juliana
The latest version of `ggseqlogo` on github now does position specific small sample correction. When there is an insufficient number of sequences to extract any information content, a warning is thrown and all information content is set to two.
