### ISSUE TITLE
The Character "U" i s missing for aa

### ISSUE THREAD

**Issue by lwlive** [omarwagih/ggseqlogo#24]
Dear,
  I have encountered  a problem when using the ggseqlogo. Can  you offer some help?
   For the following commands as example, there should be two types of aa (U or K ) at the position 8, but the figure only show "K", "U" is missing! I want to keep the "U" in the figure,  is there any way sovle this problems？ Thanks for your help!

      test<-c("SVDTPDLUREGPLNVKVG",
                   "SVDTPDLUREGPLNVKVG",
                   "SVDTPDLKREGPLNVKVG",
                   "SVDTPDLKREGPLNVKVG")
     ggseqlogo(test, method = 'prob',seq_type="aa")

Best wishes!
Wei

**Comment by omarwagih** [comment]
U isn't a valid amino acid letter. Did you try manually setting the namespace parameter?

**Comment by lwlive** [comment]
Wow，Thanks for your kind help and such a quick reply!
I have tried the namespace parameter and it  successes! Thanks again!
Here are my codes for consideration:

test<-c("SVDTPDLUREGPLNVKVG",
        "SVDTPDLUREGPLNVKVG",
        "SVDTPDLKREGPLNVKVG",
        "SVDTPDLKREGPLNVKVG")
base_seq<-paste(test,collapse = "")
base_seq_list<-unlist(strsplit(base_seq, split = ""))
base_seq_list<-unique(base_seq_list)
base_seq_list
ggseqlogo(test, method = 'prob',seq_type="other",namespace=base_seq_list)
