### ISSUE TITLE
Sample data not working

### ISSUE THREAD

**Issue by egenomics** [omarwagih/ggseqlogo#3]
> # Load the required packages
> require(ggplot2)
> require(ggseqlogo)
> 
> # Some sample data
> data(ggseqlogo_sample)
> 
> ggseqlogo( seqs_dna$sample_dna_1 )
Error in geom_logo(data = data, ...) : Missing "data" parameter!
> 
> ggseqlogo_sample
Error: object 'ggseqlogo_sample' not found

**Comment by omarwagih** [comment]
Yeah sorry about this. The github version of `ggseqlogo` is the development version and is currently undergoing some changes which aren't reflected in the tutorial yet. 

This should be updated in the coming days. For now, try uninstalling `ggseqlogo` and installing the [stable version from CRAN](https://cran.r-project.org/web/packages/ggseqlogo/index.html)

```
remove.packages('ggseqlogo')
install.packages('ggseqlogo')
```
