### ISSUE TITLE
The vignette acts weirdly in RStudio

### ISSUE THREAD

**Issue by pormr** [omarwagih/ggseqlogo#34]
The vignette page tries to open millions of web pages in external browser when you open it from RStudio (version 2023.09.1), which will quickly consume all memory on the computer (I have to kill the RStudio process to stop the propagation).

It seems to be caused by the following lines of JavaScript in the source file:
https://github.com/omarwagih/ggseqlogo/blob/4adc8f298d16f7495dc2bf8abf52bbfebcc9afcc/vignettes/ggseqlogo_introduction.Rmd#L15-L20

**Comment by omarwagih** [comment]
I've removed the auto-redirect in the vignettes which I think is causing this. This is now merged in master so to see the change reinstall 

```
devtools::install_github("omarwagih/ggseqlogo", force=T)
```

This should address the issue
