### ISSUE TITLE
Package was removed from CRAN

### ISSUE THREAD

**Issue by aviezerl** [omarwagih/ggseqlogo#36]
The following message appears on the CRAN page: 

```
Package ‘ggseqlogo’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/ggseqlogo).

Archived on 2023-11-27 as email to the maintainer was undeliverable.
```

I will be happy to help fix it if needed.

**Comment by kkrismer** [comment]
Me too! Would be great if we could get `ggseqlogo` back up on CRAN. @omarwagih please let us know if there are any specific issues we can solve.

**Comment by ammaraziz** [comment]
It's back up
https://cran.r-project.org/web/packages/ggseqlogo/index.html
