### ISSUE TITLE
Greek letters not supported

### ISSUE THREAD

**Issue by aroelo** [omarwagih/ggseqlogo#6]
Hi,

I would like to use greek letters in a custom alphabet when creating the logo.
I tried your example:

# Replace DNA characters with Greek ones
seqs_greek = chartr('ATGC', 'δεψλ', seqs_dna$MA0001.1)
ggseqlogo(seqs_greek, namespace='δεψλ', method='p')

However, I get the following error:

Error in findNamespace(letter_mat, seq_type, namespace = namespace) : 
  All letters in the namespace must be alphanumeric

I am using R studio Version 1.1.383

**Comment by omarwagih** [comment]
This works just fine for me. Please make sure you're running the latest github version. Uninstall your local version and reinstall:

```devtools::install_github("omarwagih/ggseqlogo")```
